server:
  port: '8072'

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://configserver:8071

management:
  endpoints:
    web:
      exposure:
        include: '*'
