server:
  port: '8072'

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN

management:
  endpoints:
    web:
      exposure:
        include: '*'
