server:
  port: '8090'

spring:
  application:
    name: licensing-service
  config:
    import: optional:configserver:http://configserver:8071

management:
  endpoints:
    web:
      exposure:
        include: '*'
