server:
  port: '8091'

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    testWhileIdle: 'true'
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: '{cipher}f4609209a3e75d8ac79a5e3063ce151c2cd28aa431170bb06974b9421e807b6a'
    validationQuery: SELECT 1
    platform: postgres
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

keycloak:
  auth-server-url: http://localhost:8080/auth
  credentials:
    secret: rPBRtezIYjmlhWWtEpuHJcNi2PN86RVf
  realm: spmia-realm
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: ostock

management:
  endpoints:
    web:
      exposure:
        include: '*'
