server:
  port : 8071

spring:
  application:
    name: config-server
  profiles:
    active: native

encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo

management:
  endpoints:
    web:
      exposure:
        include: "*"
